### ISSUE TITLE
Error: E5BN:E5BN:BIEF and Error: 296J:8B6S:HUCA

### ISSUE THREAD

**Issue by overwatcheddude** [flathub/org.cryptomator.Cryptomator#14]
OS: Linux / 6.0.5-arch1-1
App: 1.6.15 / flatpak-1

Neofetch:
> OS: Arch Linux x86_64 
> Kernel: 6.0.5-arch1-1 
> Uptime: 25 mins 
> Packages: 659 (pacman), 16 (flatpak) 
> Shell: bash 5.1.16 
> Resolution: 1920x1080, 1600x900 
> DE: Plasma 5.26.2 
> WM: KWin 
> Theme: [Plasma], Breeze [GTK2/3] 
> Icons: [Plasma], breeze-dark [GTK2/3] 
> Terminal: konsole 
> CPU: Intel i7-6700K (8) @ 4.300GHz 
> GPU: NVIDIA GeForce GTX 1080 
> Memory: 2833MiB / 15934MiB

This error shows up when attempting to unlock a vault. I tried both FUSE and WebDAV, but neither of them worked.

FUSE:
```
Error Code E5BN:E5BN:BIEF
org.cryptomator.common.vaults.Volume$VolumeException: Unable to mount Filesystem
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.FuseVolume.mount(FuseVolume.java:55)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.FuseVolume.mount(FuseVolume.java:42)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.Vault.unlock(Vault.java:155)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.keyloading.KeyLoadingStrategy.use(KeyLoadingStrategy.java:79)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.unlock.UnlockWorkflow.attemptUnlock(UnlockWorkflow.java:72)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:62)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:35)
	at javafx.graphics@18.0.2/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.cryptomator.frontend.fuse.mount.FuseMountException: ru.serce.jnrfuse.FuseException: Unable to mount FS
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.mount.AbstractMounter.mount(AbstractMounter.java:46)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.mount.Mounter.mount(Mounter.java:15)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.FuseVolume.mount(FuseVolume.java:53)
	... 12 more
Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:293)
	at org.cryptomator.frontend.fuse@1.3.4/org.cryptomator.frontend.fuse.mount.AbstractMounter.lambda$mount$0(AbstractMounter.java:26)
	... 1 more
Caused by: ru.serce.jnrfuse.FuseException: Unable to mount FS, return code = 1
	at ru.serce.jnrfuse.AbstractFuseFS.mount(AbstractFuseFS.java:289)
	... 2 more
```
WebDAV:
```
Error Code 296J:8B6S:HUCA
org.cryptomator.common.vaults.Volume$VolumeException: org.cryptomator.frontend.webdav.mount.Mounter$UnsupportedSystemException: No applicable mounting strategy found for this system.
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.WebDavVolume.mountServlet(WebDavVolume.java:86)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.WebDavVolume.mount(WebDavVolume.java:48)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.Vault.unlock(Vault.java:155)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.keyloading.KeyLoadingStrategy.use(KeyLoadingStrategy.java:79)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.unlock.UnlockWorkflow.attemptUnlock(UnlockWorkflow.java:72)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:62)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:35)
	at javafx.graphics@18.0.2/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.cryptomator.frontend.webdav.mount.Mounter$UnsupportedSystemException: No applicable mounting strategy found for this system.
	at org.cryptomator.frontend.webdav@1.2.8/org.cryptomator.frontend.webdav.mount.FallbackMounter.mount(FallbackMounter.java:15)
	at org.cryptomator.frontend.webdav@1.2.8/org.cryptomator.frontend.webdav.servlet.WebDavServletController.mount(WebDavServletController.java:102)
	at org.cryptomator.desktop@1.6.15/org.cryptomator.common.vaults.WebDavVolume.mountServlet(WebDavVolume.java:84)
	... 12 more

```

**Comment by overwatcheddude** [comment]
The issue has been resolved after installing [fuse2](https://archlinux.org/packages/extra/x86_64/fuse2/):
`pacman -S fuse2`

**Comment by SailReal** [comment]
Thank you for reporting the bug. With what you found out I was able to reproduce it. If fuse2 is not on the system, Cryptomator cannot mount the vault. On Ubuntu I wasn't able to reproduce it, because [Flatpak installs Fuse2 as a dependency](https://packages.ubuntu.com/jammy/flatpak). [Arch, on the other hand, installs Fuse3](https://archlinux.org/packages/extra/x86_64/flatpak/), Cryptomator currently requires Fuse2 so the problem occurs on Arch, but not on Ubuntu.

We need to check why this declared fuse dependy in Flatpak doesn't work: https://github.com/flathub/org.cryptomator.Cryptomator/blob/1ec15d8651ebf9a9dd6ed074c2fd584c903d4fa2/org.cryptomator.Cryptomator.yaml#L26-L37

**Comment by SailReal** [comment]
Got it, in line 31 we overwrite the `fusermount` command in the flatpak package with the following wrapper script placed in `build-aux/fusermount-wrapper.sh`

https://github.com/flathub/org.cryptomator.Cryptomator/blob/1ec15d8651ebf9a9dd6ed074c2fd584c903d4fa2/build-aux/fusermount-wrapper.sh#L15

`exec flatpak-spawn --host ... fusermount ...` means we are calling `fusermount` on the host system which in return means, that a user needs to install Fuse2 when using Cryptomator and what explains why it work on your system after installing Fuse2.

Tried to remove the `--host` in the wrapper script and not overwrite `fusermount` but actually call the command in the flatpack package environment but without success. The runtime then complains about missing kernel modules which is probably why this wrapper exists in the first place to call the host system.

The problem now is that Cryptomator does not check if Fuse is installed at all and if so in which version which is quite irritating especially with a packet format which is supposed to do exactly that, encapsulate runtime dependencies. Will create an issue in the Cryptomator repo to address this. Currently the workaround is exactly your described Fuse2 install. 

Will create an issue in the Cryptomator repo to address this. The workaround is and remains exactly your described, install Fuse2 (later Fuse3), but a user should know in any case what to do.
