### ISSUE TITLE
Crash when enabling Wayland window

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.cryptomator.Cryptomator#24]
```
[user@fedora user]$ flatpak run org.cryptomator.Cryptomator 
13:20:22.371 [main] INFO  o.c.common.settings.SettingsProvider - Settings loaded from /home/user/.config/Cryptomator/settings.json
13:20:22.392 [main] INFO  org.cryptomator.common.Environment - user.home: /home/user
13:20:22.393 [main] INFO  org.cryptomator.common.Environment - java.library.path: :/app/Cryptomator/lib/app:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
13:20:22.393 [main] INFO  org.cryptomator.common.Environment - user.language: de
13:20:22.393 [main] INFO  org.cryptomator.common.Environment - user.region: null
13:20:22.393 [main] INFO  org.cryptomator.common.Environment - logback.configurationFile: null
13:20:22.393 [main] INFO  org.cryptomator.common.Environment - cryptomator.settingsPath: ~/.config/Cryptomator/settings.json:~/.Cryptomator/settings.json
13:20:22.394 [main] INFO  org.cryptomator.common.Environment - cryptomator.ipcSocketPath: ~/.config/Cryptomator/ipc.socket
13:20:22.394 [main] INFO  org.cryptomator.common.Environment - cryptomator.integrationsWin.keychainPaths: null
13:20:22.394 [main] INFO  org.cryptomator.common.Environment - cryptomator.logDir: ~/.local/share/Cryptomator/logs
13:20:22.394 [main] INFO  org.cryptomator.common.Environment - cryptomator.loopbackAlias: null
13:20:22.394 [main] INFO  org.cryptomator.common.Environment - cryptomator.pluginDir: ~/.local/share/Cryptomator/plugins
13:20:22.394 [main] INFO  org.cryptomator.common.Environment - cryptomator.mountPointsDir: ~/.local/share/Cryptomator/mnt
13:20:22.394 [main] INFO  org.cryptomator.common.Environment - cryptomator.minPwLength: null
13:20:22.395 [main] INFO  org.cryptomator.common.Environment - cryptomator.appVersion: 1.6.17
13:20:22.395 [main] INFO  org.cryptomator.common.Environment - cryptomator.buildNumber: flatpak-1
13:20:22.395 [main] INFO  org.cryptomator.common.Environment - cryptomator.showTrayIcon: false
13:20:22.395 [main] INFO  org.cryptomator.common.Environment - cryptomator.p12Path: ~/.config/Cryptomator/key.p12
13:20:22.395 [main] INFO  o.cryptomator.launcher.Cryptomator - Starting Cryptomator 1.6.17 on Linux 6.1.9-200.fc37.x86_64 (amd64)
13:20:22.430 [main] INFO  org.cryptomator.ipc.Server - Spawning IPC server listening on socket /home/user/.config/Cryptomator/ipc.socket
13:20:22.653 [main] ERROR o.cryptomator.launcher.Cryptomator - Terminating due to error
java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at javafx.graphics@19/com.sun.glass.ui.gtk.GtkApplication.lambda$new$6(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at javafx.graphics@19/com.sun.glass.ui.gtk.GtkApplication.<init>(Unknown Source)
        at javafx.graphics@19/com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(Unknown Source)
        at javafx.graphics@19/com.sun.glass.ui.Application.run(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.startup(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.PlatformImpl.startup(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.startToolkit(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics@19/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
13:20:22.657 [main] INFO  o.cryptomator.launcher.Cryptomator - Exit 1
```

```
Operating System: Fedora Linux 37
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.9-200.fc37.x86_64 (64-bit)
Graphics Platform: Wayland
```

**Comment by jahed** [comment]
https://github.com/cryptomator/cryptomator/issues/985
