### ISSUE TITLE
Issue opening .vault database, not openable!

### ISSUE THREAD

**Issue by firefoxlover** [flathub/org.cryptomator.Cryptomator#25]
```
Error Code TB89:FP29:FP29
java.nio.file.NoSuchFileException: /home/user/Nextcloud/CryptCloud-verschlüsselt/CryptCloud
	at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(Unknown Source)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(Unknown Source)
	at java.base/java.nio.file.Files.readAttributes(Unknown Source)
	at org.cryptomator.cryptofs@2.5.3/org.cryptomator.cryptofs.DirStructure.checkDirStructure(DirStructure.java:54)
	at org.cryptomator.cryptofs@2.5.3/org.cryptomator.cryptofs.CryptoFileSystemProvider.checkDirStructureForVault(CryptoFileSystemProvider.java:176)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.common.vaults.VaultListManager.add(VaultListManager.java:59)
	at org.cryptomator.desktop@1.6.17/org.cryptomator.ui.addvaultwizard.ChooseExistingVaultController.chooseFileAndNext(ChooseExistingVaultController.java:87)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javafx.reflect.Trampoline.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at javafx.base@19/com.sun.javafx.reflect.MethodUtil.invoke(Unknown Source)
	at javafx.fxml@19/com.sun.javafx.fxml.MethodHelper.invoke(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$MethodHandler.invoke(Unknown Source)
	at javafx.fxml@19/javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Node.fireEvent(Unknown Source)
	at javafx.controls@19/javafx.scene.control.Button.fire(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(Unknown Source)
	at javafx.controls@19/com.sun.javafx.scene.control.inputmap.InputMap.handle(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
	at javafx.base@19/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
	at javafx.base@19/javafx.event.Event.fireEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$MouseHandler.process(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene.processMouseEvent(Unknown Source)
	at javafx.graphics@19/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
	at javafx.graphics@19/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.View.notifyMouse(Unknown Source)
	at javafx.graphics@19/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@19/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by firefoxlover** [comment]
Solution found: open the .vault file from file manager manually.

The path is displayed wrong, with A¼ instead of "ö" so I guess its a UTF-8 Error.

**Comment by SailReal** [comment]
Tried to reproduce it in Ubuntu 22.10 and Arch without success. The parent folder of the vault had the name "öäü" and the vault "ööööööööööööäääääüüüüüüüüüüüüüü". With this I could not reproduce the problem you described.

Do you use FUSE or WebDAV to mount the vault? Which version of which distro do you use with which DE?

**Comment by firefoxlover** [comment]
Its a normal filesystem. I guess it will be a fedora specific problem so I close this bug here.

I am on Fedora Kinoite 37

**Comment by firefoxlover** [comment]
It was a local error. Changing the system locale correct fixed it

**Comment by SailReal** [comment]
I'm glad you found the cause and thank you for reporting back :+1:
