### ISSUE TITLE
WebDAV mount doesn't work: gio: dav://localhost:42427/...: volume doesn’t implement mount

### ISSUE THREAD

**Issue by purejava** [flathub/org.cryptomator.Cryptomator#3]
Cryptomator 1.6.5 (flatpak-1)

Volume type `WebDAV` does not work, see @pizzadude's comment [here](https://github.com/cryptomator/cryptomator/issues/729#issuecomment-1059618066).

It fails with an Exception:
```java
14:52:38.152 [App Background Thread 004] INFO  o.c.f.w.s.WebDavServletController - WebDavServlet started: /OTGU-r-TAnLC/Test
14:52:53.206 [App Background Thread 004] INFO  o.c.f.w.s.WebDavServletController - Mounting http://localhost:42427/OTGU-r-TAnLC/Test using org.cryptomator.frontend.webdav.mount.LinuxGioMounter
14:52:53.229 [App Background Thread 004] TRACE org.cryptomator.common.vaults.Vault - Trying to close associated CryptoFS...
14:52:53.231 [JavaFX Application Thread] INFO  o.c.ui.unlock.UnlockWorkflow - Unlock of 'Test' failed.
14:52:53.232 [JavaFX Application Thread] ERROR o.c.ui.unlock.UnlockWorkflow - Unlock failed for technical reasons.
org.cryptomator.common.vaults.Volume$VolumeException: org.cryptomator.frontend.webdav.mount.Mounter$CommandFailedException: Command failed with exit code 2. Expected 0. Stderr: gio: dav://localhost:42427/OTGU-r-TAnLC/Test: Datenträger unterstützt Einhängen nicht

	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.mountServlet(WebDavVolume.java:86)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.mount(WebDavVolume.java:48)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.Vault.unlock(Vault.java:153)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.keyloading.KeyLoadingStrategy.use(KeyLoadingStrategy.java:79)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.unlock.UnlockWorkflow.attemptUnlock(UnlockWorkflow.java:71)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:61)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:34)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.cryptomator.frontend.webdav.mount.Mounter$CommandFailedException: Command failed with exit code 2. Expected 0. Stderr: gio: dav://localhost:42427/OTGU-r-TAnLC/Test: Datenträger unterstützt Einhängen nicht

	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.ProcessUtil.assertExitValue(ProcessUtil.java:28)
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.LinuxGioMounter.mount(LinuxGioMounter.java:43)
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.servlet.WebDavServletController.mount(WebDavServletController.java:102)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.mountServlet(WebDavVolume.java:84)
	... 13 common frames omitted
```

This can be reproduced by running `gio mount` from within the sandbox.
Run from inside the sandbox it states:
```
📦 org.cryptomator.Cryptomator org.cryptomator.Cryptomator]$ gio mount dav://localhost:42427/OTGU-r-TAnLC/Test
gio: dav://localhost:42427/OTGU-r-TAnLC/Test: volume doesn’t implement mount
```
whereas running from outside works:
```
ralph@fusion org.cryptomator.Cryptomator % gio mount dav://localhost:42427/OTGU-r-TAnLC/Test                              
gio: dav://localhost:42427/OTGU-r-TAnLC/Test: HTTP Error: Could not connect: Connection refused
```
(Connection refused is ok here)

I tried to adjust the `--filesystem` settings as described for [gvfs access](https://docs.flatpak.org/en/latest/sandbox-permissions.html#gvfs-access), but it did not help.

**Comment by purejava** [comment]
This took a couple of hours of analysis to find out, what the problem is.

gvfs access does require the GNOME runtime, but does not work with the Freedesktop runtime.

With these changes:
```
ralph@fusion org.cryptomator.Cryptomator % git diff                          
diff --git a/org.cryptomator.Cryptomator.yaml b/org.cryptomator.Cryptomator.yaml
index 322ed64..2f34905 100644
--- a/org.cryptomator.Cryptomator.yaml
+++ b/org.cryptomator.Cryptomator.yaml
@@ -1,8 +1,8 @@
 app-id: org.cryptomator.Cryptomator
 command: cryptomator
-runtime: org.freedesktop.Platform
-runtime-version: '21.08'
-sdk: org.freedesktop.Sdk
+runtime: org.gnome.Platform
+runtime-version: '41'
+sdk: org.gnome.Sdk
 sdk-extensions:
   - org.freedesktop.Sdk.Extension.openjdk17
 separate-locales: false
@@ -19,6 +19,7 @@ finish-args:
   - --talk-name=org.freedesktop.secrets
   - --talk-name=org.gnome.keyring
   - --talk-name=org.kde.kwalletd5
+  - --filesystem=xdg-run/gvfs
   - --talk-name=org.gtk.vfs.*
 cleanup:
   - /include
ralph@fusion org.cryptomator.Cryptomator %
```

it's mounting the dav URL:
```
ralph@fusion org.cryptomator.Cryptomator % flatpak run org.cryptomator.Cryptomator 
06:52:20.691 [main] DEBUG org.cryptomator.common.Environment - user.home: /home/ralph
06:52:20.693 [main] DEBUG org.cryptomator.common.Environment - java.library.path: :/app/Cryptomator/lib/app:/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - user.language: de
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - user.region: null
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - logback.configurationFile: null
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.settingsPath: ~/.config/Cryptomator/settings.json:~/.Cryptomator/settings.json
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.ipcSocketPath: ~/.config/Cryptomator/ipc.socket
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.keychainPath: null
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.logDir: ~/.local/share/Cryptomator/logs
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.pluginDir: ~/.local/share/Cryptomator/plugins
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.mountPointsDir: ~/.local/share/Cryptomator/mnt
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.minPwLength: null
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.appVersion: 1.6.5
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.buildNumber: flatpak-1
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - cryptomator.showTrayIcon: false
06:52:20.694 [main] DEBUG org.cryptomator.common.Environment - fuse.experimental: false
06:52:20.716 [main] DEBUG org.cryptomator.common.ShutdownHook - Registered shutdown hook.
06:52:20.758 [main] DEBUG org.cryptomator.common.settings.SettingsProvider - Attempting to load settings from /home/ralph/.config/Cryptomator/settings.json
06:52:20.786 [main] INFO org.cryptomator.common.settings.SettingsProvider - Settings loaded from /home/ralph/.config/Cryptomator/settings.json
06:52:20.790 [main] INFO  org.cryptomator.launcher.Cryptomator - Starting Cryptomator 1.6.5 on Linux 5.16.15-arch1-1 (amd64)
06:52:20.809 [main] INFO  org.cryptomator.ipc.Server - Spawning IPC server listening on socket /home/ralph/.config/Cryptomator/ipc.socket
Gtk-Message: 06:52:20.950: Failed to load module "canberra-gtk-module"
Gtk-Message: 06:52:20.951: Failed to load module "canberra-gtk-module"
06:52:21.336 [JavaFX Application Thread] INFO  o.c.ui.launcher.FxApplicationStarter - JavaFX Runtime started.
06:52:32.451 [App Scheduled Executor 01] INFO  o.c.common.settings.SettingsProvider - Settings saved to /home/ralph/.config/Cryptomator/settings.json
06:52:38.123 [App Background Thread 003] INFO  o.c.frontend.webdav.WebDavServer - Binding server socket to localhost:42427
06:52:38.136 [App Background Thread 003] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@15b95816{HTTP/1.1, (http/1.1)}{localhost:42427}
06:52:38.138 [App Background Thread 003] INFO  org.eclipse.jetty.server.Server - jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 17.0.1+12
06:52:38.189 [App Background Thread 003] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@2a3cb466{/,null,AVAILABLE}
Defaulting Uptime to NOIMPL due to (java.lang.UnsupportedOperationException) Implementation not available in this environment
06:52:38.191 [App Background Thread 003] INFO  org.eclipse.jetty.server.Server - Started Server@d17436b{STARTING}[10.0.6,sto=0] @-1ms
06:52:38.191 [App Background Thread 003] INFO  o.c.frontend.webdav.WebDavServer - WebDavServer started.
06:52:38.224 [App Background Thread 003] INFO  o.e.j.s.s.DefaultSessionIdManager - Session workerName=node0
06:52:38.228 [App Background Thread 003] INFO  o.a.j.w.server.AbstractWebdavServlet - authenticate-header = Basic realm="Jackrabbit Webdav Server"
06:52:38.228 [App Background Thread 003] INFO  o.a.j.w.server.AbstractWebdavServlet - csrf-protection = null
06:52:38.228 [App Background Thread 003] INFO  o.a.j.w.server.AbstractWebdavServlet - createAbsoluteURI = true
06:52:38.229 [App Background Thread 003] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@4e0d9c75{/mD1otu-Sljc1/Test,null,AVAILABLE}
06:52:38.229 [App Background Thread 003] INFO  o.c.f.w.s.WebDavServletController - WebDavServlet started: /mD1otu-Sljc1/Test
06:52:53.270 [App Background Thread 003] INFO  o.c.f.w.s.WebDavServletController - Mounting http://localhost:42427/mD1otu-Sljc1/Test using org.cryptomator.frontend.webdav.mount.LinuxGioMounter
06:52:53.467 [JavaFX Application Thread] INFO  o.c.ui.unlock.UnlockWorkflow - Unlock of 'Test' succeeded.
```

The keychain backends `GNOME Keyring`, `KDE Wallet` and `KeePassXC` also work with the changes mentioned above.

**Comment by purejava** [comment]
Nevertheless, clicking on `Reveal drive` fails.
![Bildschirmfoto vom 2022-03-19 07-04-43](https://user-images.githubusercontent.com/1822238/159115189-c129434a-856a-4dd5-a96a-330e06db24c9.png)
And clicking on the Find button ...
![Bildschirmfoto vom 2022-03-19 07-06-43](https://user-images.githubusercontent.com/1822238/159115193-cb64fb95-e84e-4805-bf69-6ad48bd6f09f.png)
I seems that revealing the drive need special treatment for WebDAV.

**Comment by purejava** [comment]
This is the according log:
```
06:54:36.116 [JavaFX Application Thread] WARN  o.c.u.unlock.UnlockSuccessController - Reveal failed.
org.cryptomator.common.vaults.Volume$VolumeException: org.cryptomator.frontend.webdav.mount.ProcessUtil$CommandTimeoutException: Command timed out.
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.reveal(WebDavVolume.java:95)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.Vault.reveal(Vault.java:192)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.common.VaultService$RevealVaultTask.call(VaultService.java:120)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.common.VaultService$RevealVaultTask.call(VaultService.java:102)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.cryptomator.frontend.webdav.mount.ProcessUtil$CommandTimeoutException: Command timed out.
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.ProcessUtil.waitFor(ProcessUtil.java:68)
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.ProcessUtil.startAndWaitFor(ProcessUtil.java:48)
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.VfsMountingStrategy$MountImpl.reveal(VfsMountingStrategy.java:32)
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.VfsMountingStrategy$MountImpl.reveal(VfsMountingStrategy.java:37)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.reveal(WebDavVolume.java:93)
	... 8 common frames omitted
```

**Comment by overheadhunter** [comment]
How about using `webdav:` instead of `dav:` (see Cryptomator's settings)?

In general I would prefer the more generic freedesktop runtime, but if the gnome one is more reliable, let's change it.

**Comment by purejava** [comment]
> How about using `webdav:` instead of `dav:` (see Cryptomator's settings)?

Mount fails with:
```
12:37:38.805 [JavaFX Application Thread] INFO  o.c.ui.launcher.FxApplicationStarter - JavaFX Runtime started.
12:37:55.952 [App Background Thread 003] INFO  o.c.u.a.CreateNewVaultPasswordController - Created vault at /home/ralph/Test
12:37:56.963 [App Scheduled Executor 01] INFO  o.c.common.settings.SettingsProvider - Settings saved to /home/ralph/.config/Cryptomator/settings.json
12:38:02.026 [App Scheduled Executor 02] INFO  o.c.common.settings.SettingsProvider - Settings saved to /home/ralph/.config/Cryptomator/settings.json
12:38:06.224 [App Scheduled Executor 01] INFO  o.c.common.settings.SettingsProvider - Settings saved to /home/ralph/.config/Cryptomator/settings.json
12:38:08.595 [App Scheduled Executor 02] INFO  o.c.common.settings.SettingsProvider - Settings saved to /home/ralph/.config/Cryptomator/settings.json
12:38:18.943 [App Scheduled Executor 01] INFO  o.c.common.settings.SettingsProvider - Settings saved to /home/ralph/.config/Cryptomator/settings.json
12:38:22.105 [App Background Thread 004] INFO  o.c.frontend.webdav.WebDavServer - Binding server socket to localhost:42427
12:38:22.114 [App Background Thread 004] INFO  o.e.jetty.server.AbstractConnector - Started ServerConnector@235ace17{HTTP/1.1, (http/1.1)}{localhost:42427}
12:38:22.117 [App Background Thread 004] INFO  org.eclipse.jetty.server.Server - jetty-10.0.6; built: 2021-06-29T15:28:56.259Z; git: 37e7731b4b142a882d73974ff3bec78d621bd674; jvm 17.0.1+12
12:38:22.139 [App Background Thread 004] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@71a92a12{/,null,AVAILABLE}
Defaulting Uptime to NOIMPL due to (java.lang.UnsupportedOperationException) Implementation not available in this environment
12:38:22.140 [App Background Thread 004] INFO  org.eclipse.jetty.server.Server - Started Server@467f9106{STARTING}[10.0.6,sto=0] @-1ms
12:38:22.140 [App Background Thread 004] INFO  o.c.frontend.webdav.WebDavServer - WebDavServer started.
12:38:22.171 [App Background Thread 004] INFO  o.e.j.s.s.DefaultSessionIdManager - Session workerName=node0
12:38:22.174 [App Background Thread 004] INFO  o.a.j.w.server.AbstractWebdavServlet - authenticate-header = Basic realm="Jackrabbit Webdav Server"
12:38:22.175 [App Background Thread 004] INFO  o.a.j.w.server.AbstractWebdavServlet - csrf-protection = null
12:38:22.175 [App Background Thread 004] INFO  o.a.j.w.server.AbstractWebdavServlet - createAbsoluteURI = true
12:38:22.175 [App Background Thread 004] INFO  o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@670cf47c{/ZZlgC6rM8U3T/Test,null,AVAILABLE}
12:38:22.175 [App Background Thread 004] INFO  o.c.f.w.s.WebDavServletController - WebDavServlet started: /ZZlgC6rM8U3T/Test
12:38:37.229 [App Background Thread 004] INFO  o.c.f.w.s.WebDavServletController - Mounting http://localhost:42427/ZZlgC6rM8U3T/Test using org.cryptomator.frontend.webdav.mount.LinuxGioMounter
12:38:37.277 [JavaFX Application Thread] INFO  o.c.ui.unlock.UnlockWorkflow - Unlock of 'Test' failed.
12:38:37.278 [JavaFX Application Thread] ERROR o.c.ui.unlock.UnlockWorkflow - Unlock failed for technical reasons.
org.cryptomator.common.vaults.Volume$VolumeException: org.cryptomator.frontend.webdav.mount.Mounter$CommandFailedException: Command failed with exit code 2. Expected 0. Stderr: gio: webdav://localhost:42427/ZZlgC6rM8U3T/Test: Ort kann nicht eingehängt werden

	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.mountServlet(WebDavVolume.java:86)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.mount(WebDavVolume.java:48)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.Vault.unlock(Vault.java:153)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.keyloading.KeyLoadingStrategy.use(KeyLoadingStrategy.java:79)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.unlock.UnlockWorkflow.attemptUnlock(UnlockWorkflow.java:71)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:61)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.ui.unlock.UnlockWorkflow.call(UnlockWorkflow.java:34)
	at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:1426)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.cryptomator.frontend.webdav.mount.Mounter$CommandFailedException: Command failed with exit code 2. Expected 0. Stderr: gio: webdav://localhost:42427/ZZlgC6rM8U3T/Test: Ort kann nicht eingehängt werden

	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.ProcessUtil.assertExitValue(ProcessUtil.java:28)
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.mount.LinuxGioMounter.mount(LinuxGioMounter.java:43)
	at org.cryptomator.frontend.webdav@1.2.6/org.cryptomator.frontend.webdav.servlet.WebDavServletController.mount(WebDavServletController.java:102)
	at org.cryptomator.desktop@1.6.5/org.cryptomator.common.vaults.WebDavVolume.mountServlet(WebDavVolume.java:84)
	... 13 common frames omitted
```
> In general I would prefer the more generic freedesktop runtime, but if the gnome one is more reliable, let's change it.

The documentation [states](https://docs.flatpak.org/en/latest/available-runtimes.html) that the GNOME runtime is based on the Freedesktop runtime and adds features (like GVFS).

**Comment by overheadhunter** [comment]
> > In general I would prefer the more generic freedesktop runtime, but if the gnome one is more reliable, let's change it.
> The documentation states that the GNOME runtime is based on the Freedesktop runtime and adds features (like GVFS).

Yes, I am aware of that. The only drawback is that the runtimes are usually the largest parts during installation of a Flatpak package. And the more "basic" a runtime is, the more likely it is already installed in the requested version.

**Comment by purejava** [comment]
WebDAV uses `gio open` [to reveal the vault](https://github.com/cryptomator/webdav-nio-adapter/blob/fb6e35c278c24ccd51418e3c8b84bbae9a1b4a27/src/main/java/org/cryptomator/frontend/webdav/mount/LinuxGioMounter.java#L54).

@infeo describes MIME handling [here](https://github.com/cryptomator/cryptomator/issues/1539#issuecomment-781431080). Irritatingly this works on the host whereas is does not within the sandbox, although both environments do not have a MIME assocciation for dav:
```
ralph@fusion ~ % gio mime x-scheme-handler/dav                               
No default applications for »x-scheme-handler/dav«
```
(same within the sandbox)

Any ideas?

**Comment by overheadhunter** [comment]
I found some issues mentioning `--filesystem=xdg-run/gvfsd` in this context... Just a wild guess, but worth a try  🤔

**Comment by purejava** [comment]
Besides the fact that both environments do not have a MIME association for dav, they do differ when it comes to `inode/mount-point`. On my GNOME box (host) the settings are as follows:
```
ralph@fusion org.cryptomator.Cryptomator % xdg-mime query default inode/directory  
org.gnome.Nautilus.desktop
ralph@fusion org.cryptomator.Cryptomator % gio mime inode/mount-point              
Standardanwendung für »inode/mount-point«: org.gnome.Nautilus.desktop
Registrierte Anwendungen:
	org.gnome.Nautilus.desktop
Keine empfohlenen Anwendungen
```

The same for the sandbox:
```
ralph@fusion org.cryptomator.Cryptomator % flatpak run --command=sh --devel org.cryptomator.Cryptomator
[📦 org.cryptomator.Cryptomator org.cryptomator.Cryptomator]$ xdg-mime query default inode/directory
sh: xdg-mime: Kommando nicht gefunden.
[📦 org.cryptomator.Cryptomator org.cryptomator.Cryptomator]$ gio mime inode/mount-point
Keine Vorgabeanwendungen für »inode/mount-point«
[📦 org.cryptomator.Cryptomator org.cryptomator.Cryptomator]$ 
```

As far as I understand the MIME handling of the sandbox via the involved xdg portals, the MIME handling looks up the MIME conf in the sandbox and falls back to the host.

It was not possible to set the `inode/mount-point` mime to `org.gnome.Nautilus.desktop` within the sandbox.

Then I tried to set this on the host. It allows the flatpaked Cryptomator to reveal the vault:
```
ralph@fusion org.cryptomator.Cryptomator % gio mime x-scheme-handler/dav `xdg-mime query default inode/directory`
```

Maybe there is a way to set this for the sandbox?

I still do not understand how this is configured on the host. Where does `gio open` rely on `inode/mount-point` and how is this wired together?

**Comment by purejava** [comment]
I've found a discussion on the flatpak channel about this very problem: [pop up saying that no app is available to open the file](https://matrix.to/#/!RfXaBjokqHAbzZrgHz%3Amatrix.org/%24FvpTZZwIRawDUkprA7P87o5r-uOByuON_5cBjin6v3I).

The solution is to set the MIME association on the **host**:
```bash
gio mime x-scheme-handler/dav `xdg-mime query default inode/directory`
```

This adds something like `x-scheme-handler/dav=org.gnome.Nautilus.desktop;` to the `~/.config/mimeapps.list`. Depending on what the file browser on your host is.

In theory, to achive the same within the sandbox on installing the app, something like this:
```bash
if ! [ -f "$XDG_CONFIG_HOME/.config/mimeapps.list" ]; then
  echo "[Added Associations]" > $XDG_CONFIG_HOME/.config/mimeapps.list
fi
if ! grep -Fxq "`xdg-mime query default inode/directory`;" "$XDG_CONFIG_HOME/.config/mimeapps.list" ; then
  sed -i "/Added Associations/a x-scheme-handler/dav=`xdg-mime query default inode/directory`;" $XDG_CONFIG_HOME/.config/mimeapps.list
fi
```
could be added to the manifest:
```yaml
post-install:
      - MOUNT_POINT=$(xdg-mime query default inode/directory);
      - if ! [ -f "$XDG_CONFIG_HOME/ ...
```

Unfortunately the sandbox does not know `xdg-mime` (see [comment #3](https://github.com/flathub/org.cryptomator.Cryptomator/issues/3#issuecomment-1076714775)) and `gio mime inode/mount-point` does not return a value, so it's impossible to determine the file browser on the host from within the sandbox.

From my point of view, this leaves us with a workaround to set the MIME association on the host with the command above to get WebDAV working. And the GNOME runtime is required.

**Comment by overheadhunter** [comment]
During a major mount mechanism rework, we changed the reveal mechanism. It will no longer use `gio open` but standard Java APIs. Furthermore we will add a fallback mechanism that will allow the user to get the URL and mount it with any program manually.

We hope to publish a beta within a few weeks, which might be relevant to test with this issue as well.
